import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
	Sidebar,
	SidebarContent,
	SidebarProvider,
	SidebarTrigger,
} from "@/components/ui/sidebar";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<SidebarProvider>
					<div className="flex h-screen w-screen">
						<Sidebar className="border-r bg-primary/10">
							<SidebarContent>
								{/* Brand Name */}
								<div className="p-6 border-b">
									<h1 className="text-3xl font-light" style={{ fontFamily: 'serif', color: 'rgb(148 92 57)' }}>Qode</h1>
								</div>
								{/* Navigation links */}
								<nav className="space-y-2 p-4">
									<Link
										href="/"
										className="block px-3 py-2 hover:bg-primary transition-colors text-foreground hover:text-primary-foreground"
									>
										Home
									</Link>
									<Link
										href="/portfolio"
										className="block px-3 py-2 hover:bg-primary transition-colors text-foreground hover:text-primary-foreground"
									>
										Portfolio
									</Link>
								</nav>
							</SidebarContent>
						</Sidebar>
						<main className="flex-1 overflow-auto w-full h-full">
							{children}
						</main>
					</div>
				</SidebarProvider>
			</body>
		</html>
	);
}
